use crate::models::*;
use rusqlite::{params, Connection, OptionalExtension};
use std::path::Path;
use uuid::Uuid;

pub struct Storage {
    conn: Connection,
}
impl Storage {
    pub fn open(path: &Path) -> Result<Self, String> {
        let conn = Connection::open(path).map_err(|e| e.to_string())?;
        conn.execute_batch("PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON;
          CREATE TABLE IF NOT EXISTS profiles (id TEXT PRIMARY KEY, name TEXT NOT NULL, engine TEXT NOT NULL, host TEXT, port INTEGER, database_name TEXT, username TEXT, sqlite_path TEXT, source_path TEXT, allow_writes INTEGER NOT NULL DEFAULT 0, tls_mode TEXT NOT NULL DEFAULT 'verifyIdentity', created_at TEXT NOT NULL);
          CREATE TABLE IF NOT EXISTS schema_cache (profile_id TEXT PRIMARY KEY REFERENCES profiles(id) ON DELETE CASCADE, payload TEXT NOT NULL);
          CREATE TABLE IF NOT EXISTS chat_sessions (id TEXT PRIMARY KEY, profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE, title TEXT NOT NULL, share_results INTEGER NOT NULL, mode TEXT NOT NULL DEFAULT 'plan', created_at TEXT NOT NULL);
          CREATE TABLE IF NOT EXISTS chat_messages (id TEXT PRIMARY KEY, session_id TEXT NOT NULL REFERENCES chat_sessions(id) ON DELETE CASCADE, role TEXT NOT NULL, content TEXT NOT NULL, sql TEXT, created_at TEXT NOT NULL);
          CREATE TABLE IF NOT EXISTS query_outputs (id TEXT PRIMARY KEY, session_id TEXT NOT NULL REFERENCES chat_sessions(id) ON DELETE CASCADE, source_message_id TEXT, title TEXT NOT NULL, sql TEXT NOT NULL, result_payload TEXT, collapsed INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, UNIQUE(session_id, source_message_id));
          CREATE TABLE IF NOT EXISTS query_history (id TEXT PRIMARY KEY, profile_id TEXT NOT NULL REFERENCES profiles(id) ON DELETE CASCADE, sql TEXT NOT NULL, executed_at TEXT NOT NULL);
          CREATE TABLE IF NOT EXISTS app_migrations (id TEXT PRIMARY KEY, applied_at TEXT NOT NULL);")
          .map_err(|e| e.to_string())?;
        let has_source = conn
            .prepare("PRAGMA table_info(profiles)")
            .map_err(|e| e.to_string())?
            .query_map([], |r| r.get::<_, String>(1))
            .map_err(|e| e.to_string())?
            .collect::<Result<Vec<_>, _>>()
            .map_err(|e| e.to_string())?
            .iter()
            .any(|c| c == "source_path");
        if !has_source {
            conn.execute("ALTER TABLE profiles ADD COLUMN source_path TEXT", [])
                .map_err(|e| e.to_string())?;
        }
        let profile_columns = conn
            .prepare("PRAGMA table_info(profiles)")
            .map_err(|e| e.to_string())?
            .query_map([], |r| r.get::<_, String>(1))
            .map_err(|e| e.to_string())?
            .collect::<Result<Vec<_>, _>>()
            .map_err(|e| e.to_string())?;
        if !profile_columns
            .iter()
            .any(|column| column == "allow_writes")
        {
            conn.execute(
                "ALTER TABLE profiles ADD COLUMN allow_writes INTEGER NOT NULL DEFAULT 0",
                [],
            )
            .map_err(|e| e.to_string())?;
        }
        if !profile_columns.iter().any(|column| column == "tls_mode") {
            conn.execute(
                "ALTER TABLE profiles ADD COLUMN tls_mode TEXT NOT NULL DEFAULT 'verifyIdentity'",
                [],
            )
            .map_err(|e| e.to_string())?;
        }
        let has_mode = conn
            .prepare("PRAGMA table_info(chat_sessions)")
            .map_err(|e| e.to_string())?
            .query_map([], |r| r.get::<_, String>(1))
            .map_err(|e| e.to_string())?
            .collect::<Result<Vec<_>, _>>()
            .map_err(|e| e.to_string())?
            .iter()
            .any(|c| c == "mode");
        if !has_mode {
            conn.execute(
                "ALTER TABLE chat_sessions ADD COLUMN mode TEXT NOT NULL DEFAULT 'plan'",
                [],
            )
            .map_err(|e| e.to_string())?;
        }
        // Backfill query cards for SQL generated by earlier application builds exactly once.
        let outputs_backfilled: bool = conn
            .query_row(
                "SELECT EXISTS(SELECT 1 FROM app_migrations WHERE id='query-output-backfill-v1')",
                [],
                |r| r.get(0),
            )
            .map_err(|e| e.to_string())?;
        if !outputs_backfilled {
            conn.execute("INSERT OR IGNORE INTO query_outputs(id,session_id,source_message_id,title,sql,collapsed,created_at,updated_at) SELECT 'message-'||id,session_id,id,'Generated SQL',sql,0,created_at,created_at FROM chat_messages WHERE sql IS NOT NULL AND trim(sql)<>''",[]).map_err(|e|e.to_string())?;
            conn.execute(
                "INSERT INTO app_migrations(id,applied_at)VALUES('query-output-backfill-v1',?1)",
                [chrono::Utc::now().to_rfc3339()],
            )
            .map_err(|e| e.to_string())?;
        }
        Ok(Self { conn })
    }
    pub fn list_profiles(&self) -> Result<Vec<ConnectionProfile>, String> {
        let mut stmt = self.conn.prepare("SELECT id,name,engine,host,port,database_name,username,sqlite_path,source_path,allow_writes,tls_mode,created_at FROM profiles ORDER BY name").map_err(|e|e.to_string())?;
        let result = stmt
            .query_map([], profile_row)
            .map_err(|e| e.to_string())?
            .collect::<Result<_, _>>()
            .map_err(|e| e.to_string());
        result
    }
    pub fn profile(&self, id: &str) -> Result<ConnectionProfile, String> {
        self.conn.query_row("SELECT id,name,engine,host,port,database_name,username,sqlite_path,source_path,allow_writes,tls_mode,created_at FROM profiles WHERE id=?1", [id], profile_row).optional().map_err(|e|e.to_string())?.ok_or_else(|| "Connection profile was not found.".into())
    }
    pub fn source_profile_at(&self, path: &str) -> Result<Option<ConnectionProfile>, String> {
        self.conn.query_row("SELECT id,name,engine,host,port,database_name,username,sqlite_path,source_path,allow_writes,tls_mode,created_at FROM profiles WHERE engine='source' AND source_path=?1 LIMIT 1", [path], profile_row).optional().map_err(|e|e.to_string())
    }
    pub fn save_profile(&self, input: ProfileInput) -> Result<ConnectionProfile, String> {
        let id = input.id.unwrap_or_else(|| Uuid::new_v4().to_string());
        let created_at = chrono::Utc::now().to_rfc3339();
        let engine = engine_name(&input.engine);
        self.conn.execute("INSERT INTO profiles (id,name,engine,host,port,database_name,username,sqlite_path,source_path,allow_writes,tls_mode,created_at) VALUES (?1,?2,?3,?4,?5,?6,?7,?8,?9,?10,?11,?12) ON CONFLICT(id) DO UPDATE SET name=excluded.name,engine=excluded.engine,host=excluded.host,port=excluded.port,database_name=excluded.database_name,username=excluded.username,sqlite_path=excluded.sqlite_path,source_path=excluded.source_path,allow_writes=excluded.allow_writes,tls_mode=excluded.tls_mode", params![id,input.name,engine,input.host,input.port,input.database,input.username,input.sqlite_path,input.source_path,input.allow_writes,tls_mode_name(&input.tls_mode),created_at]).map_err(|e|e.to_string())?;
        self.profile(&id)
    }
    pub fn delete_profile(&self, id: &str) -> Result<(), String> {
        self.conn
            .execute("DELETE FROM profiles WHERE id=?1", [id])
            .map_err(|e| e.to_string())?;
        Ok(())
    }
    pub fn save_schema(&self, id: &str, schema: &SchemaSnapshot) -> Result<(), String> {
        let data = serde_json::to_string(schema).map_err(|e| e.to_string())?;
        self.conn.execute("INSERT INTO schema_cache(profile_id,payload) VALUES(?1,?2) ON CONFLICT(profile_id) DO UPDATE SET payload=excluded.payload",params![id,data]).map_err(|e|e.to_string())?;
        Ok(())
    }
    pub fn schema(&self, id: &str) -> Result<SchemaSnapshot, String> {
        let data: Option<String> = self
            .conn
            .query_row(
                "SELECT payload FROM schema_cache WHERE profile_id=?1",
                [id],
                |r| r.get(0),
            )
            .optional()
            .map_err(|e| e.to_string())?;
        data.ok_or_else(|| "No schema is cached yet. Refresh the schema first.".into())
            .and_then(|s| serde_json::from_str(&s).map_err(|e| e.to_string()))
    }
    pub fn create_session(&self, profile_id: &str, share: bool) -> Result<ChatSession, String> {
        let s = ChatSession {
            id: Uuid::new_v4().to_string(),
            profile_id: profile_id.into(),
            title: "New chat".into(),
            share_results: share,
            mode: AgentMode::Plan,
            created_at: chrono::Utc::now().to_rfc3339(),
        };
        self.conn.execute("INSERT INTO chat_sessions(id,profile_id,title,share_results,mode,created_at)VALUES(?1,?2,?3,?4,?5,?6)",params![s.id,s.profile_id,s.title,s.share_results,mode_name(&s.mode),s.created_at]).map_err(|e|e.to_string())?;
        Ok(s)
    }
    pub fn sessions(&self, profile_id: &str) -> Result<Vec<ChatSession>, String> {
        let mut stmt=self.conn.prepare("SELECT id,profile_id,title,share_results,mode,created_at FROM chat_sessions WHERE profile_id=?1 ORDER BY created_at DESC").map_err(|e|e.to_string())?;
        let result = stmt
            .query_map([profile_id], chat_session_row)
            .map_err(|e| e.to_string())?
            .collect::<Result<_, _>>()
            .map_err(|e| e.to_string());
        result
    }
    pub fn session(&self, id: &str) -> Result<ChatSession, String> {
        self.conn.query_row("SELECT id,profile_id,title,share_results,mode,created_at FROM chat_sessions WHERE id=?1",[id],chat_session_row).optional().map_err(|e|e.to_string())?.ok_or_else(||"Chat session was not found.".into())
    }
    pub fn messages(&self, session_id: &str) -> Result<Vec<ChatMessage>, String> {
        let mut stmt=self.conn.prepare("SELECT id,role,content,created_at,sql FROM chat_messages WHERE session_id=?1 ORDER BY created_at").map_err(|e|e.to_string())?;
        let result = stmt
            .query_map([session_id], |r| {
                Ok(ChatMessage {
                    id: r.get(0)?,
                    role: r.get(1)?,
                    content: r.get(2)?,
                    created_at: r.get(3)?,
                    sql: r.get(4)?,
                })
            })
            .map_err(|e| e.to_string())?
            .collect::<Result<_, _>>()
            .map_err(|e| e.to_string());
        result
    }
    pub fn add_message(
        &self,
        session_id: &str,
        role: &str,
        content: &str,
    ) -> Result<ChatMessage, String> {
        let m = ChatMessage {
            id: Uuid::new_v4().to_string(),
            role: role.into(),
            content: content.into(),
            created_at: chrono::Utc::now().to_rfc3339(),
            sql: extract_sql(content),
        };
        self.conn.execute("INSERT INTO chat_messages(id,session_id,role,content,sql,created_at)VALUES(?1,?2,?3,?4,?5,?6)",params![m.id,session_id,m.role,m.content,m.sql,m.created_at]).map_err(|e|e.to_string())?;
        Ok(m)
    }
    pub fn set_session_title_from_message(&self, id: &str, message: &str) -> Result<(), String> {
        let title = message
            .split_whitespace()
            .collect::<Vec<_>>()
            .join(" ")
            .chars()
            .take(64)
            .collect::<String>();
        if !title.is_empty() {
            self.conn
                .execute(
                    "UPDATE chat_sessions SET title=?2 WHERE id=?1 AND title='New chat'",
                    params![id, title],
                )
                .map_err(|e| e.to_string())?;
        }
        Ok(())
    }
    pub fn query_outputs(&self, session_id: &str) -> Result<Vec<QueryOutput>, String> {
        let mut stmt=self.conn.prepare("SELECT id,session_id,source_message_id,title,sql,result_payload,collapsed,created_at,updated_at FROM query_outputs WHERE session_id=?1 ORDER BY created_at DESC").map_err(|e|e.to_string())?;
        let result = stmt
            .query_map([session_id], query_output_row)
            .map_err(|e| e.to_string())?
            .collect::<Result<_, _>>()
            .map_err(|e| e.to_string());
        result
    }
    pub fn query_output(&self, id: &str) -> Result<QueryOutput, String> {
        self.conn.query_row("SELECT id,session_id,source_message_id,title,sql,result_payload,collapsed,created_at,updated_at FROM query_outputs WHERE id=?1",[id],query_output_row).optional().map_err(|e|e.to_string())?.ok_or_else(||"Query output was not found.".into())
    }
    pub fn save_query_output(
        &self,
        session_id: &str,
        source_message_id: Option<&str>,
        title: &str,
        sql: &str,
    ) -> Result<QueryOutput, String> {
        if let Some(message_id) = source_message_id {
            if let Some(existing)=self.conn.query_row("SELECT id,session_id,source_message_id,title,sql,result_payload,collapsed,created_at,updated_at FROM query_outputs WHERE session_id=?1 AND source_message_id=?2",params![session_id,message_id],query_output_row).optional().map_err(|e|e.to_string())?{return Ok(existing);}
        }
        let now = chrono::Utc::now().to_rfc3339();
        let id = Uuid::new_v4().to_string();
        self.conn.execute("INSERT INTO query_outputs(id,session_id,source_message_id,title,sql,collapsed,created_at,updated_at)VALUES(?1,?2,?3,?4,?5,0,?6,?6)",params![id,session_id,source_message_id,title,sql,now]).map_err(|e|e.to_string())?;
        self.query_output(&id)
    }
    pub fn update_query_output(
        &self,
        id: &str,
        sql: &str,
        result: Option<&QueryResult>,
    ) -> Result<QueryOutput, String> {
        let payload = result
            .map(serde_json::to_string)
            .transpose()
            .map_err(|e| e.to_string())?;
        self.conn
            .execute(
                "UPDATE query_outputs SET sql=?2,result_payload=?3,updated_at=?4 WHERE id=?1",
                params![id, sql, payload, chrono::Utc::now().to_rfc3339()],
            )
            .map_err(|e| e.to_string())?;
        self.query_output(id)
    }
    pub fn set_query_output_collapsed(&self, id: &str, collapsed: bool) -> Result<(), String> {
        self.conn
            .execute(
                "UPDATE query_outputs SET collapsed=?2,updated_at=?3 WHERE id=?1",
                params![id, collapsed, chrono::Utc::now().to_rfc3339()],
            )
            .map_err(|e| e.to_string())?;
        Ok(())
    }
    pub fn delete_query_output(&self, id: &str) -> Result<(), String> {
        self.conn
            .execute("DELETE FROM query_outputs WHERE id=?1", [id])
            .map_err(|e| e.to_string())?;
        Ok(())
    }
    pub fn add_query(&self, profile_id: &str, sql: &str) -> Result<(), String> {
        self.conn
            .execute(
                "INSERT INTO query_history(id,profile_id,sql,executed_at)VALUES(?1,?2,?3,?4)",
                params![
                    Uuid::new_v4().to_string(),
                    profile_id,
                    sql,
                    chrono::Utc::now().to_rfc3339()
                ],
            )
            .map_err(|e| e.to_string())?;
        Ok(())
    }
    pub fn delete_session(&self, id: &str) -> Result<(), String> {
        self.conn
            .execute("DELETE FROM chat_sessions WHERE id=?1", [id])
            .map_err(|e| e.to_string())?;
        Ok(())
    }
    pub fn set_session_sharing(&self, id: &str, share: bool) -> Result<(), String> {
        self.conn
            .execute(
                "UPDATE chat_sessions SET share_results=?2 WHERE id=?1",
                params![id, share],
            )
            .map_err(|e| e.to_string())?;
        Ok(())
    }
    pub fn set_session_mode(&self, id: &str, mode: &AgentMode) -> Result<(), String> {
        self.conn
            .execute(
                "UPDATE chat_sessions SET mode=?2 WHERE id=?1",
                params![id, mode_name(mode)],
            )
            .map_err(|e| e.to_string())?;
        Ok(())
    }
}
fn profile_row(r: &rusqlite::Row<'_>) -> rusqlite::Result<ConnectionProfile> {
    let engine: String = r.get(2)?;
    let tls_mode: String = r.get(10)?;
    Ok(ConnectionProfile {
        id: r.get(0)?,
        name: r.get(1)?,
        engine: parse_engine(&engine),
        host: r.get(3)?,
        port: r.get(4)?,
        database: r.get(5)?,
        username: r.get(6)?,
        sqlite_path: r.get(7)?,
        source_path: r.get(8)?,
        allow_writes: r.get(9)?,
        tls_mode: parse_tls_mode(&tls_mode),
        created_at: r.get(11)?,
    })
}
fn engine_name(engine: &DatabaseEngine) -> &'static str {
    match engine {
        DatabaseEngine::Auto => "auto",
        DatabaseEngine::Postgres => "postgres",
        DatabaseEngine::Mysql => "mysql",
        DatabaseEngine::Sqlserver => "sqlserver",
        DatabaseEngine::Sqlite => "sqlite",
        DatabaseEngine::Source => "source",
    }
}
fn parse_engine(s: &str) -> DatabaseEngine {
    match s {
        "postgres" => DatabaseEngine::Postgres,
        "mysql" => DatabaseEngine::Mysql,
        "sqlserver" => DatabaseEngine::Sqlserver,
        "sqlite" => DatabaseEngine::Sqlite,
        "source" => DatabaseEngine::Source,
        _ => DatabaseEngine::Auto,
    }
}
fn tls_mode_name(mode: &TlsMode) -> &'static str {
    match mode {
        TlsMode::VerifyIdentity => "verifyIdentity",
        TlsMode::Require => "require",
        TlsMode::Disable => "disable",
    }
}
fn parse_tls_mode(value: &str) -> TlsMode {
    match value {
        "require" => TlsMode::Require,
        "disable" => TlsMode::Disable,
        _ => TlsMode::VerifyIdentity,
    }
}
fn mode_name(mode: &AgentMode) -> &'static str {
    match mode {
        AgentMode::Plan => "plan",
        AgentMode::Chat => "chat",
        AgentMode::Direct => "direct",
    }
}
fn parse_mode(value: &str) -> AgentMode {
    match value {
        "chat" => AgentMode::Chat,
        "direct" => AgentMode::Direct,
        _ => AgentMode::Plan,
    }
}
fn chat_session_row(r: &rusqlite::Row<'_>) -> rusqlite::Result<ChatSession> {
    let mode: String = r.get(4)?;
    Ok(ChatSession {
        id: r.get(0)?,
        profile_id: r.get(1)?,
        title: r.get(2)?,
        share_results: r.get(3)?,
        mode: parse_mode(&mode),
        created_at: r.get(5)?,
    })
}
fn query_output_row(r: &rusqlite::Row<'_>) -> rusqlite::Result<QueryOutput> {
    let payload: Option<String> = r.get(5)?;
    let result = payload
        .map(|value| {
            serde_json::from_str(&value).map_err(|error| {
                rusqlite::Error::FromSqlConversionFailure(
                    5,
                    rusqlite::types::Type::Text,
                    Box::new(error),
                )
            })
        })
        .transpose()?;
    Ok(QueryOutput {
        id: r.get(0)?,
        session_id: r.get(1)?,
        source_message_id: r.get(2)?,
        title: r.get(3)?,
        sql: r.get(4)?,
        result,
        collapsed: r.get(6)?,
        created_at: r.get(7)?,
        updated_at: r.get(8)?,
    })
}
fn extract_sql(text: &str) -> Option<String> {
    let start = text.find("```sql")? + 6;
    let rest = &text[start..];
    let end = rest.find("```")?;
    Some(rest[..end].trim().into())
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn migrates_profiles_and_cascades_project_deletion() {
        let path =
            std::env::temp_dir().join(format!("querycraft-store-test-{}.sqlite", Uuid::new_v4()));
        let old = Connection::open(&path).unwrap();
        old.execute_batch("CREATE TABLE profiles (id TEXT PRIMARY KEY, name TEXT NOT NULL, engine TEXT NOT NULL, host TEXT, port INTEGER, database_name TEXT, username TEXT, sqlite_path TEXT, created_at TEXT NOT NULL);").unwrap();
        drop(old);
        let store = Storage::open(&path).unwrap();
        let profile = store
            .save_profile(ProfileInput {
                id: None,
                name: "Example".into(),
                engine: DatabaseEngine::Source,
                host: None,
                port: None,
                database: None,
                username: None,
                password: None,
                sqlite_path: None,
                source_path: Some("project".into()),
                allow_writes: false,
                tls_mode: TlsMode::VerifyIdentity,
            })
            .unwrap();
        assert_eq!(
            store.source_profile_at("project").unwrap().unwrap().id,
            profile.id
        );
        let session = store.create_session(&profile.id, true).unwrap();
        assert_eq!(session.mode, AgentMode::Plan);
        store.delete_profile(&profile.id).unwrap();
        assert!(store.session(&session.id).is_err());
        drop(store);
        let _ = std::fs::remove_file(&path);
        let _ = std::fs::remove_file(path.with_extension("sqlite-wal"));
        let _ = std::fs::remove_file(path.with_extension("sqlite-shm"));
    }
    #[test]
    fn query_outputs_persist_independently_from_chat_messages() {
        let path =
            std::env::temp_dir().join(format!("agentsql-output-test-{}.sqlite", Uuid::new_v4()));
        let store = Storage::open(&path).unwrap();
        let profile = store
            .save_profile(ProfileInput {
                id: None,
                name: "Fixture".into(),
                engine: DatabaseEngine::Source,
                host: None,
                port: None,
                database: None,
                username: None,
                password: None,
                sqlite_path: None,
                source_path: Some("fixture".into()),
                allow_writes: false,
                tls_mode: TlsMode::VerifyIdentity,
            })
            .unwrap();
        let session = store.create_session(&profile.id, false).unwrap();
        let message = store
            .add_message(&session.id, "assistant", "```sql\nSELECT 1 AS value\n```")
            .unwrap();
        let output = store
            .save_query_output(
                &session.id,
                Some(&message.id),
                "Generated query",
                message.sql.as_deref().unwrap(),
            )
            .unwrap();
        let result = QueryResult {
            columns: vec!["value".into()],
            rows: vec![vec![serde_json::json!(1)]],
            elapsed_ms: 2,
            truncated: false,
        };
        let output = store
            .update_query_output(&output.id, &output.sql, Some(&result))
            .unwrap();
        store.set_query_output_collapsed(&output.id, true).unwrap();
        drop(store);

        let reopened = Storage::open(&path).unwrap();
        let outputs = reopened.query_outputs(&session.id).unwrap();
        assert_eq!(outputs.len(), 1);
        assert!(outputs[0].collapsed);
        assert_eq!(outputs[0].result.as_ref().unwrap().rows.len(), 1);
        reopened.delete_query_output(&outputs[0].id).unwrap();
        assert!(reopened.query_outputs(&session.id).unwrap().is_empty());
        assert_eq!(reopened.messages(&session.id).unwrap().len(), 1);
        drop(reopened);
        let reopened_again = Storage::open(&path).unwrap();
        assert!(reopened_again
            .query_outputs(&session.id)
            .unwrap()
            .is_empty());
        assert_eq!(reopened_again.messages(&session.id).unwrap().len(), 1);
        drop(reopened_again);
        let _ = std::fs::remove_file(&path);
        let _ = std::fs::remove_file(path.with_extension("sqlite-wal"));
        let _ = std::fs::remove_file(path.with_extension("sqlite-shm"));
    }
}
